### ISSUE TITLE
Does the selection of 'teleporting' make any difference on final results?

### ISSUE THREAD

**Issue by zwx8981** [chihyaoma/regretful-agent#2]
Hi, I have a question. Does the selection of 'teleporting' make any difference on final results? In terms of both success rate and navigation length. Thank you.

**Comment by chihyaoma** [comment]
Hi, 

In my preliminary experiments, this doesn't affect the performance much. The reason why I enabled `teleporting` is simply because it was faster in terms of getting the new environment state, _i.e._, faster data loading.
